site_name: Passport.js
nav:
  - Home: "index.md"
  - Project Structure: "pages/project-structure.md"
  - Setting up Express.js: "pages/express-setup.md"
  - Creating Login Form: "pages/login-form.md"
  - Using passport-local: "pages/using-passport-local.md"
  - Logging in: "pages/logging-in.md"

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: en

copyright: Copyright &copy; 2023  Michael Lei and Devynn Nguyen
