site_name: Passport User Documentation
nav:
  - Home: "index.md"
  - Project Overview: "pages/login-form-tutorial.md"
  - Project Structure: "pages/project-structure.md"
  - Express.js: "pages/express-setup.md"
  - Database: "pages/db-setup.md"
  - Login Form: "pages/login-form.md"
  - Passport: "pages/passport-local.md"
  - Log in: "pages/logging-in.md"
  - Troubleshooting: "pages/troubleshoot.md"
  - Glossary: "pages/glossary.md"

markdown_extensions:
  - toc:
      toc_depth: 3
  - attr_list
  - footnotes
  - admonition
  - codehilite
  - def_list
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

theme:
  name: material
  logo: assets/passport.svg

  features:
    - navigation.footer
    - navigation.top
    - content.code.copy
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: en

copyright: Copyright &copy; 2023  Michael Lei and Devynn Nguyen
